# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfam_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(622, 461)
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        form.setFont(font)
        form.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.verticalLayoutWidget = QtWidgets.QWidget(form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 170, 431, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_eng_turk = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_eng_turk.setFont(font)
        self.pushButton_eng_turk.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_eng_turk.setMouseTracking(False)
        self.pushButton_eng_turk.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_eng_turk.setCheckable(False)
        self.pushButton_eng_turk.setChecked(False)
        self.pushButton_eng_turk.setObjectName("pushButton_eng_turk")
        self.verticalLayout.addWidget(self.pushButton_eng_turk)
        self.pushButton_turk_eng = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_turk_eng.setFont(font)
        self.pushButton_turk_eng.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_turk_eng.setObjectName("pushButton_turk_eng")
        self.verticalLayout.addWidget(self.pushButton_turk_eng)
        self.pushButton_ikinci_hal = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ikinci_hal.setFont(font)
        self.pushButton_ikinci_hal.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_ikinci_hal.setObjectName("pushButton_ikinci_hal")
        self.verticalLayout.addWidget(self.pushButton_ikinci_hal)
        self.pushButton_ucuncu_hal = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ucuncu_hal.setFont(font)
        self.pushButton_ucuncu_hal.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_ucuncu_hal.setObjectName("pushButton_ucuncu_hal")
        self.verticalLayout.addWidget(self.pushButton_ucuncu_hal)
        self.label = QtWidgets.QLabel(form)
        self.label.setGeometry(QtCore.QRect(240, 90, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 255, 0);")
        self.label.setObjectName("label")

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Form"))
        self.pushButton_eng_turk.setText(_translate("form", "İngilizce_Türkçe"))
        self.pushButton_turk_eng.setText(_translate("form", "Türkçe-İngilizce"))
        self.pushButton_ikinci_hal.setText(_translate("form", "İkinci hali"))
        self.pushButton_ucuncu_hal.setText(_translate("form", "Üçüncü hali"))
        self.label.setText(_translate("form", "ANASAYFA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    ui = Ui_form()
    ui.setupUi(form)
    form.show()
    sys.exit(app.exec_())
